server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      # ====== CẤU HÌNH CORS TOÀN CỤC (cho FE JS gọi sang) ======
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://127.0.0.1:5500"
              - "http://localhost:5500"
              - "http://localhost:63342"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      # Tránh header CORS bị nhân đôi
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      # ====== KHAI BÁO CÁC ROUTE ĐẾN MICROSERVICE CON ======
      routes:
        # Route đến cinema-service (Spring)
        - id: cinema-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/cinemas/**

        # Route đến movie-service (Node) – nếu sau này dùng
        - id: movie-service
          uri: http://localhost:4002
          predicates:
            - Path=/api/movies/**
              # Showtime (auto-create) cũng nằm trong movie-service
        - id: showtime-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/showtimes/**
        - id: booking-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/bookings/**
        - id: payment-service
          uri: http://localhost:8004
          predicates:
            - Path=/api/payment/**



management:
  endpoints:
    web:
      exposure:
        include: "*"
