#server:
#  port: 8082
#spring:
#  datasource:
#    url: "jdbc:mysql://localhost:3306/booking"
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  data:
#    redis:
#      host: localhost
#      port: 6379

server:
  port: 8082

spring:
  application:
    name: showtime-service

  datasource:
    url: jdbc:mysql://localhost:3306/cinemax_showtimes
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update          #  update schema tự động
    show-sql: true              # in SQL ra console cho dễ debug
    properties:
      hibernate:
        format_sql: true        # format SQL cho đẹp
